// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2rJOhPy2EonoAmHfvfcv5hhJYuaSyBfU',
    appId: '1:631739280431:web:4eaa14c60e84c70cad6ada',
    messagingSenderId: '631739280431',
    projectId: 'labinpocket',
    authDomain: 'labinpocket.firebaseapp.com',
    storageBucket: 'labinpocket.firebasestorage.app',
    measurementId: 'G-0V7Q7S633K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFJsT_QruT8D_jT2oPy_a0HpdEHbtidY',
    appId: '1:631739280431:android:333a4269683852cbad6ada',
    messagingSenderId: '631739280431',
    projectId: 'labinpocket',
    storageBucket: 'labinpocket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYC5S5hKV3tKUdhMxNdg6tEHlp-3UIVlY',
    appId: '1:631739280431:ios:129c273733c3bfbead6ada',
    messagingSenderId: '631739280431',
    projectId: 'labinpocket',
    storageBucket: 'labinpocket.firebasestorage.app',
    iosBundleId: 'com.example.labInPocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYC5S5hKV3tKUdhMxNdg6tEHlp-3UIVlY',
    appId: '1:631739280431:ios:129c273733c3bfbead6ada',
    messagingSenderId: '631739280431',
    projectId: 'labinpocket',
    storageBucket: 'labinpocket.firebasestorage.app',
    iosBundleId: 'com.example.labInPocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2rJOhPy2EonoAmHfvfcv5hhJYuaSyBfU',
    appId: '1:631739280431:web:e6138f38c57076c9ad6ada',
    messagingSenderId: '631739280431',
    projectId: 'labinpocket',
    authDomain: 'labinpocket.firebaseapp.com',
    storageBucket: 'labinpocket.firebasestorage.app',
    measurementId: 'G-7VMHVNXWNF',
  );
}
